# docker-compose.dev.yml
version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: sysdm_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # ⚠️ ПРИ ИЗМЕНЕНИИ ПАРОЛЯ ВЫПОЛНИТЕ:
      # ⚠️ docker-compose exec db psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'НОВЫЙ_ПАРОЛЬ';"
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - sysdm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  #    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sysdm_api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      # Основные настройки
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      # Дополнительные переменные
      TZ: ${TZ:-Europe/Moscow}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Монтируем исходный код для разработки
      - .:/app
    env_file:
      - .env
    networks:
      - sysdm_network
    restart: unless-stopped
    #    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sysdm.rule=Host(`sysdm.local`)"
      - "traefik.http.services.sysdm.loadbalancer.server.port=8000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/app/static:ro
    networks:
      - sysdm_network
    restart: unless-stopped

# === MeshCentral (билдим локально из официального Dockerfile) ===
  mongo:
    image: mongo:6
    container_name: mesh_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mesh_mongo_data:/data/db
    networks:
      - sysdm_network


  meshcentral:
    build:
      context: .
      dockerfile: Dockerfile.meshcentral
    container_name: meshcentral
    restart: unless-stopped
    ports:
      - "4443:443"
    environment:
      MONGO_URL: "mongodb://mongo:27017/meshcentral"
      TZ: "Europe/Moscow"
    volumes:
      - ./meshcentral/meshcentral-data:/meshcentral/meshcentral-data
    depends_on:
      - mongo
    networks:
      - sysdm_network


networks:
  sysdm_network:
    driver: bridge
    name: sysdm_network

volumes:
  mesh_mongo_data:
    driver: local
  meshcentral_data:
    driver: local
  postgres_data:
    driver: local
